encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.showPage, name="showPage" ),
    path("search/", views.searchResult, name="searchResult"),
    path("addNew/", views.addNew, name="addNew"),
    path("edit/<str:title>/", views.edit, name="edit"),
    path("saveEdit/", views.saveEdit, name="saveEdit"),
    path("random/", views.findRandom, name="findRandom")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path("wiki/", include("encyclopedia.urls") )

]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import re
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
from . import util
from . import markdown2


class AddNewEntry(forms.Form):
    newEntryTitle = forms.CharField(label="Title")
    newEntryContent = forms.CharField(label="Content", widget=forms.Textarea)


#index page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


#Search bar
def searchResult(request):

    #get the value of the search input query
    q = request.GET.get('q')

    #call the util function on the value of d input query and store in variable x
    x = util.get_entry(q)

    #Show entries that dont exactly match but similar to the searched entry
    if x == None:
            entries = util.list_entries()
            matches = []

            for entry in entries:
                if re.search(rf'{q}',entry, re.IGNORECASE):
                    matches.append(entry)

            return render(request, "encyclopedia/index.html", {
                "entries": matches
            })

    else:
        return render(request, "encyclopedia/content.html", {
            "singleResult":markdown2.markdown(util.get_entry(q)),
            "title": q
        })


#Show content of entry. If none is found, show an error page.
def showPage(request, title):
    x = util.get_entry(title)

    if x == None:
        return render(request, "encyclopedia/error.html")
    else:
        return render(request, "encyclopedia/content.html", {
            "singleResult":markdown2.markdown(util.get_entry(title)),
            "title": title
        })
    

#Add new page. If entry already exist, show an error
def addNew(request):
    if request.method == "POST":
        form = AddNewEntry(request.POST)

        if form.is_valid():
            title = form.cleaned_data["newEntryTitle"]
            content = form.cleaned_data["newEntryContent"]
            if title in util.list_entries():
                return render(request, "encyclopedia/duplicatepage.html")
            else:
                util.save_entry(title, content)
                return render(request, "encyclopedia/content.html", {
                    "singleResult":markdown2.markdown(util.get_entry(title)),
                    "title": title
                })
        else:
            return render(request, "encyclopedia/addnew.html", {
                "form": form
            })
        
    return render(request, "encyclopedia/addnew.html", {
        "form": AddNewEntry
    })


#Edit the content of an entry
def edit(request, title):
    entryForEdit = util.get_entry(title)

    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "singleResult": entryForEdit
    })


#Function to save the edited entry and render
def saveEdit(request):
    if request.method == "POST":
        content = request.POST.get('content')
        title = request.POST.get('title')

        util.save_entry(title, content)
        return render(request, "encyclopedia/content.html", {
            "singleResult":markdown2.markdown(util.get_entry(title)),
            "title": title
        })


#Random function for displaying an entry    
def findRandom(request):
    allEntries = util.list_entries()
    print(allEntries)
    randomEntry = random.choice(allEntries)
    content = markdown2.markdown(util.get_entry(randomEntry))

    return render(request, "encyclopedia/content.html", {
        "singleResult": content,
        "title": randomEntry
    })
    
    

encyclopedia/templates/encyclopedia/addnew.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add New
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:addNew' %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <div>
            <input style="margin-top: 20px;" type="submit" value="Save" />
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

    {{singleResult|safe}}

    <a href="{% url 'encyclopedia:edit' title %}">Edit Page</a>

{% endblock %}

encyclopedia/templates/encyclopedia/duplicatepage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Duplicate Page
{% endblock %}

{% block body %}
    

    <h1>Error...This page already exist!!!</h1>

    <a href="{% url 'encyclopedia:addNew' %}">Try Again</a>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>

    
    <form action="{% url 'encyclopedia:saveEdit' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="title">Title:</label>
            <input id="title" name="title" value="{{ title|safe }}"/>
        </div>

        <div><label for="content">Content:</label></div>
        <div>
            <textarea id="content" name="content">{{singleResult}}</textarea>
        </div>
        
        <div style="margin: auto;">
            <input type="submit" value="Save"/>
        </div>
    </form>
    

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    

    <h1>404 Error. Page not found!</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:showPage' title=entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:searchResult'  %}" method="GET">
                    <input class="search" type="text" name="q" value="" placeholder="Search Encyclopedia">
                    <input type="submit" >
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:addNew' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:findRandom' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>